# Generated by Django 5.2 on 2025-04-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="drinking_party",
            fields=[
                (
                    "drinking_party_id",
                    models.AutoField(primary_key=True, verbose_name="飲み会ID"),
                ),
                (
                    "drinking_party_name",
                    models.CharField(max_length=255, verbose_name="飲み会名"),
                ),
                ("date", models.DateField(verbose_name="開催日")),
                (
                    "location",
                    models.CharField(
                        max_length=255, null=True, blank=True, verbose_name="場所"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        max_length=255, null=True, blank=True, verbose_name="備考"
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
            ],
            options={
                "verbose_name": "飲み会テーブル",
                "verbose_name_plural": "飲み会テーブル",
            },
        ),
        migrations.CreateModel(
            name="drinking_party_payment",
            fields=[
                (
                    "id",
                    models.AutoField(verbose_name="ID"),
                ),  # 自動生成されるIDを明示的に指定
                ("drinking_party_id", models.IntegerField(verbose_name="飲み会ID")),
                ("user_id", models.IntegerField(verbose_name="ユーザーID")),
                ("fee", models.IntegerField(verbose_name="支払い金額")),
                ("is_paid", models.BooleanField(verbose_name="支払い済みフラグ")),
                (
                    "is_advance_payment",
                    models.BooleanField(verbose_name="建て替えフラグ"),
                ),
                (
                    "remarks",
                    models.CharField(
                        max_length=255, null=True, blank=True, verbose_name="備考"
                    ),
                ),
            ],
            options={
                "verbose_name": "飲み会支払いテーブル",
                "verbose_name_plural": "飲み会支払いテーブル",
                "unique_together": {("drinking_party_id", "user_id")},  # 複合キーを指定
            },
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "user_id",
                    models.AutoField(primary_key=True, verbose_name="ユーザーID"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="ユーザー名"),
                ),
                (
                    "mail",
                    models.EmailField(
                        max_length=255,
                        null=True,
                        blank=True,
                        verbose_name="メールアドレス",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザーマスタ",
                "verbose_name_plural": "ユーザーマスタ",
            },
        ),
    ]
